#ifndef BECM_4G_CAPI_API_ERROR_DEFNS_H
#define BECM_4G_CAPI_API_ERROR_DEFNS_H
typedef enum E_ERROR_DEFNS {
    ERROR_CODE_SUCCESS = 0,
    ERROR_CODE_MEMORY_ALLOCATION_FALIED,
    ERROR_CODE_INVALID_HANDLE,
    ERROR_CODE_INVALID_PARAM,
    ERROR_CODE_INVALID_TYPE,
    ERROR_CODE_CONNECTION_FAILED,
    ERROR_CODE_CALL_RESPONSE_TIMEOUT,
    ERROR_CODE_TYPE_RCVD_INVALID,
    ERROR_CODE_LENGTH_RCVD_INVALID,
    ERROR_CODE_TLV_COUNT_DIDNOT_MATCH,
    ERROR_CODE_TLV_LENGTH_MISMATCH_WITH_TOTAL_LENGTH,
    ERROR_CODE_API_EXEC_FAILED,
    ERROR_CODE_API_DISCONNECT_FAILED
} E_ERROR_DEFNS, *P_E_ERROR_DEFNS;

#endif
