#ifndef GUISTRUCTS_H
#define GUISTRUCTS_H

#include "uconn_Event.h"

enum {
    CUST_IDLE_EVENT=1235,
    CUST_ENABLE_EVENT=1236,
    CUST_SEARCH_EVENT=1237,
    CUST_CONNECTING_EVENT=1238,
    CUST_CONNECTED_EVENT=1239,
    CUST_DISCONNECTING_EVENT=1240,
    CUST_DISABLE_EVENT=1241,

    CUST_AUTO_EVENT=1244,
    CUST_MANUAL_EVENT=1245,

    CUST_DEBUG_EVENT=1246,
    CUST_INFO_EVENT=1247,
    CUST_ERROR_EVENT=1248,

    CUST_SER_LOG_ENABLED_EVENT=1249,
    CUST_SER_LOG_DISABLED_EVENT=1250,

    CUST_SYS_DEVICE_ERROR_EVENT=1251,
    CUST_SYS_DEVICE_NOT_OPEN_EVENT=1252,
    CUST_SYS_DEVICE_OPEN_EVENT=1253,
    CUST_SYS_DISCONNECTED_EVENT=1254,
    CUST_SYS_DEVICE_CONNECTED_EVENT=1255,
    CUST_SYS_DEVICE_DISCONNECTED_EVENT=1256,

    CUST_CM_SERVER_CONN_LOST=1257,

    CUST_CONNECTION_CHANGE_EVENT = 1258,
    CUST_SCAN_RESPONSE_EVENT = 1259,
    CUST_WIFI_PREF_EVENT = 1260,
    CUST_WIFI_STATS_RSP_EVENT = 1261,
    CUST_WIFI_PASSWORD_EVENT = 1262,
    CUST_3G_STATS_EVENT = 1263,
    CUST_SHOW_NM_SETTINGS_EVT = 1264,
    CUST_ADD_INITIAL_TECHS_EVT = 1265,
    CUST_HANDLE_NM_STATE_CHANGE_EVT = 1266,
    CUST_HANDLE_NM_NETWORK_NAME_EVT = 1267,
    CUST_SHOW_GOT_NM_PARAM = 1268,
    CUST_USSD_RESPONSE = 1269,
    CUST_NM_CONNECT_FAIL_EVT = 1270,
    CUST_WIFI_DISABLED_NOTI_EVT = 1271,
    CUST_INITIAL_RAS_PROFILE_EVT = 1272,
    CUST_ERROR_DISPLAY_EVT =1273,
	CUST_VPN_PROFILE_LIST_EVT = 1274,
	CUST_VPN_CLIENT_LIST_EVT = 1275,
    CUST_VPN_CONNECT_EVT = 1276,
	CUST_VPN_DISCONNECT_EVT = 1277

};


struct NMStateChange {

    ETechSelect techId;
    ENMStateForBM state;

};

struct NetworkListEncoded {

    string networkList;
    ETechSelect techId;


};

struct NMGetParam {
    ETechSelect techId;
    Get_NM_Param paramId;
    string param;
};

struct NMErrorInfo{
    string errorStr;
    ETechSelect techId;
    ENM_Error errorType;
	U_UINT32 errorCode;
};

#endif // GUISTRUCTS_H
